// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_H
#define WINRT_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/Microsoft.Windows.Devices.Midi2.h"
#include "winrt/impl/Microsoft.Windows.Devices.Midi2.ServiceConfig.2.h"
#include "winrt/impl/Windows.Data.Json.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Microsoft.Windows.Devices.Midi2.VirtualPatchBay.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinition<D>::IsEnabled() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition)->get_IsEnabled(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinition<D>::IsEnabled(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition)->put_IsEnabled(value));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinition<D>::EndpointMatchCriteria() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition)->get_EndpointMatchCriteria(&value));
        return winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinition<D>::EndpointMatchCriteria(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition)->put_EndpointMatchCriteria(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinition<D>::GetConfigJson() const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition)->GetConfigJson(&result));
        return winrt::Windows::Data::Json::JsonObject{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinitionFactory<D>::CreateInstance(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& matchCriteria) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionFactory)->CreateInstance(*(void**)(&matchCriteria), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayDestinationDefinitionStatics<D>::CreateFromConfigJson(param::hstring const& jsonSection) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionStatics)->CreateFromConfigJson(*(void**)(&jsonSection), &result));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::IsTransportAvailable() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->get_IsTransportAvailable(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::TransportId() const
    {
        winrt::guid value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->get_TransportId(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::GetRoutes() const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->GetRoutes(&result));
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::GetRoute(winrt::guid const& routeId) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->GetRoute(impl::bind_in(routeId), &result));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::CreateRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig const& creationConfig) const
    {
        winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationResult result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->CreateRoute(*(void**)(&creationConfig), put_abi(result)));
        return result;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::UpdateRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig const& updateConfig) const
    {
        winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateResult result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->UpdateRoute(*(void**)(&updateConfig), put_abi(result)));
        return result;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::RemoveRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig const& removalConfig) const
    {
        bool result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->RemoveRoute(*(void**)(&removalConfig), &result));
        return result;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayManagerStatics<D>::GetRouteStatus(winrt::guid const& routeId) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics)->GetRouteStatus(impl::bind_in(routeId), &result));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteStatus{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteCreationConfig<D>::Definition() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfig)->get_Definition(&value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteCreationConfig<D>::Definition(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfig)->put_Definition(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteCreationConfigFactory<D>::CreateInstance(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition const& definition) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfigFactory)->CreateInstance(*(void**)(&definition), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::RouteId() const
    {
        winrt::guid value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_RouteId(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Name() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_Name(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Name(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->put_Name(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Description() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_Description(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Description(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->put_Description(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::IsEnabled() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_IsEnabled(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::IsEnabled(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->put_IsEnabled(value));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Sources() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_Sources(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::Destinations() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->get_Destinations(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinition<D>::GetConfigJson() const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition)->GetConfigJson(&result));
        return winrt::Windows::Data::Json::JsonObject{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinitionFactory<D>::CreateInstance(param::hstring const& name) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionFactory)->CreateInstance(*(void**)(&name), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinitionFactory<D>::CreateInstance2(param::hstring const& name, param::hstring const& description) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionFactory)->CreateInstance2(*(void**)(&name), *(void**)(&description), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteDefinitionStatics<D>::CreateFromConfigJson(param::hstring const& jsonSection) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionStatics)->CreateFromConfigJson(*(void**)(&jsonSection), &result));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteRemovalConfig<D>::RouteId() const
    {
        winrt::guid value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfig)->get_RouteId(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteRemovalConfig<D>::RouteId(winrt::guid const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfig)->put_RouteId(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteRemovalConfigFactory<D>::CreateInstance(winrt::guid const& routeId) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfigFactory)->CreateInstance(impl::bind_in(routeId), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteStatus<D>::RouteId() const
    {
        winrt::guid value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteStatus)->get_RouteId(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteStatus<D>::IsEnabled() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteStatus)->get_IsEnabled(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteUpdateConfig<D>::RouteId() const
    {
        winrt::guid value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfig)->get_RouteId(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteUpdateConfig<D>::RouteId(winrt::guid const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfig)->put_RouteId(impl::bind_in(value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBayRouteUpdateConfigFactory<D>::CreateInstance(winrt::guid const& routeId) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfigFactory)->CreateInstance(impl::bind_in(routeId), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinition<D>::IsEnabled() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition)->get_IsEnabled(&value));
        return value;
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinition<D>::IsEnabled(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition)->put_IsEnabled(value));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinition<D>::EndpointMatchCriteria() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition)->get_EndpointMatchCriteria(&value));
        return winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinition<D>::EndpointMatchCriteria(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition)->put_EndpointMatchCriteria(*(void**)(&value)));
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinition<D>::GetConfigJson() const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition)->GetConfigJson(&result));
        return winrt::Windows::Data::Json::JsonObject{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinitionFactory<D>::CreateInstance(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& matchCriteria) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionFactory)->CreateInstance(*(void**)(&matchCriteria), &value));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_IMidiVirtualPatchBaySourceDefinitionStatics<D>::CreateFromConfigJson(param::hstring const& jsonSection) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionStatics)->CreateFromConfigJson(*(void**)(&jsonSection), &result));
        return winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition{ result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition>
    {
        int32_t __stdcall get_IsEnabled(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IsEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_EndpointMatchCriteria(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria>(this->shim().EndpointMatchCriteria());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_EndpointMatchCriteria(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().EndpointMatchCriteria(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetConfigJson(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Data::Json::JsonObject>(this->shim().GetConfigJson());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionFactory>
    {
        int32_t __stdcall CreateInstance(void* matchCriteria, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const*>(&matchCriteria)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionStatics> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionStatics>
    {
        int32_t __stdcall CreateFromConfigJson(void* jsonSection, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition>(this->shim().CreateFromConfigJson(*reinterpret_cast<hstring const*>(&jsonSection)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics>
    {
        int32_t __stdcall get_IsTransportAvailable(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsTransportAvailable());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_TransportId(winrt::guid* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::guid>(this->shim().TransportId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetRoutes(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>>(this->shim().GetRoutes());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetRoute(winrt::guid routeId, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(this->shim().GetRoute(*reinterpret_cast<winrt::guid const*>(&routeId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall CreateRoute(void* creationConfig, struct struct_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_MidiVirtualPatchBayRouteCreationResult* result) noexcept final try
        {
            zero_abi<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationResult>(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationResult>(this->shim().CreateRoute(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig const*>(&creationConfig)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall UpdateRoute(void* updateConfig, struct struct_Microsoft_Windows_Devices_Midi2_VirtualPatchBay_MidiVirtualPatchBayRouteUpdateResult* result) noexcept final try
        {
            zero_abi<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateResult>(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateResult>(this->shim().UpdateRoute(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig const*>(&updateConfig)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall RemoveRoute(void* removalConfig, bool* result) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *result = detach_from<bool>(this->shim().RemoveRoute(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig const*>(&removalConfig)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetRouteStatus(winrt::guid routeId, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteStatus>(this->shim().GetRouteStatus(*reinterpret_cast<winrt::guid const*>(&routeId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfig> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfig>
    {
        int32_t __stdcall get_Definition(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(this->shim().Definition());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_Definition(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Definition(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfigFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfigFactory>
    {
        int32_t __stdcall CreateInstance(void* definition, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition const*>(&definition)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition>
    {
        int32_t __stdcall get_RouteId(winrt::guid* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::guid>(this->shim().RouteId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Name(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().Name());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_Name(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Name(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Description(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().Description());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_Description(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Description(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_IsEnabled(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IsEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Sources(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition>>(this->shim().Sources());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Destinations(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition>>(this->shim().Destinations());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetConfigJson(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Data::Json::JsonObject>(this->shim().GetConfigJson());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionFactory>
    {
        int32_t __stdcall CreateInstance(void* name, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(this->shim().CreateInstance(*reinterpret_cast<hstring const*>(&name)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall CreateInstance2(void* name, void* description, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(this->shim().CreateInstance2(*reinterpret_cast<hstring const*>(&name), *reinterpret_cast<hstring const*>(&description)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionStatics> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionStatics>
    {
        int32_t __stdcall CreateFromConfigJson(void* jsonSection, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(this->shim().CreateFromConfigJson(*reinterpret_cast<hstring const*>(&jsonSection)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfig> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfig>
    {
        int32_t __stdcall get_RouteId(winrt::guid* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::guid>(this->shim().RouteId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_RouteId(winrt::guid value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RouteId(*reinterpret_cast<winrt::guid const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfigFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfigFactory>
    {
        int32_t __stdcall CreateInstance(winrt::guid routeId, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig>(this->shim().CreateInstance(*reinterpret_cast<winrt::guid const*>(&routeId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteStatus> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteStatus>
    {
        int32_t __stdcall get_RouteId(winrt::guid* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::guid>(this->shim().RouteId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_IsEnabled(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfig> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfig>
    {
        int32_t __stdcall get_RouteId(winrt::guid* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::guid>(this->shim().RouteId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_RouteId(winrt::guid value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RouteId(*reinterpret_cast<winrt::guid const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfigFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfigFactory>
    {
        int32_t __stdcall CreateInstance(winrt::guid routeId, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig>(this->shim().CreateInstance(*reinterpret_cast<winrt::guid const*>(&routeId)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition>
    {
        int32_t __stdcall get_IsEnabled(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IsEnabled(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsEnabled(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_EndpointMatchCriteria(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria>(this->shim().EndpointMatchCriteria());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_EndpointMatchCriteria(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().EndpointMatchCriteria(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall GetConfigJson(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Data::Json::JsonObject>(this->shim().GetConfigJson());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionFactory> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionFactory>
    {
        int32_t __stdcall CreateInstance(void* matchCriteria, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const*>(&matchCriteria)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionStatics> : produce_base<D, winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionStatics>
    {
        int32_t __stdcall CreateFromConfigJson(void* jsonSection, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition>(this->shim().CreateFromConfigJson(*reinterpret_cast<hstring const*>(&jsonSection)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
}
WINRT_EXPORT namespace winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay
{
    inline MidiVirtualPatchBayDestinationDefinition::MidiVirtualPatchBayDestinationDefinition() :
        MidiVirtualPatchBayDestinationDefinition(impl::call_factory_cast<MidiVirtualPatchBayDestinationDefinition(*)(winrt::Windows::Foundation::IActivationFactory const&), MidiVirtualPatchBayDestinationDefinition>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MidiVirtualPatchBayDestinationDefinition>(); }))
    {
    }
    inline MidiVirtualPatchBayDestinationDefinition::MidiVirtualPatchBayDestinationDefinition(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& matchCriteria) :
        MidiVirtualPatchBayDestinationDefinition(impl::call_factory<MidiVirtualPatchBayDestinationDefinition, IMidiVirtualPatchBayDestinationDefinitionFactory>([&](IMidiVirtualPatchBayDestinationDefinitionFactory const& f) { return f.CreateInstance(matchCriteria); }))
    {
    }
    inline auto MidiVirtualPatchBayDestinationDefinition::CreateFromConfigJson(param::hstring const& jsonSection)
    {
        return impl::call_factory<MidiVirtualPatchBayDestinationDefinition, IMidiVirtualPatchBayDestinationDefinitionStatics>([&](IMidiVirtualPatchBayDestinationDefinitionStatics const& f) { return f.CreateFromConfigJson(jsonSection); });
    }
    inline auto MidiVirtualPatchBayManager::IsTransportAvailable()
    {
        return impl::call_factory_cast<bool(*)(IMidiVirtualPatchBayManagerStatics const&), MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([](IMidiVirtualPatchBayManagerStatics const& f) { return f.IsTransportAvailable(); });
    }
    inline auto MidiVirtualPatchBayManager::TransportId()
    {
        return impl::call_factory_cast<winrt::guid(*)(IMidiVirtualPatchBayManagerStatics const&), MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([](IMidiVirtualPatchBayManagerStatics const& f) { return f.TransportId(); });
    }
    inline auto MidiVirtualPatchBayManager::GetRoutes()
    {
        return impl::call_factory_cast<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition>(*)(IMidiVirtualPatchBayManagerStatics const&), MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([](IMidiVirtualPatchBayManagerStatics const& f) { return f.GetRoutes(); });
    }
    inline auto MidiVirtualPatchBayManager::GetRoute(winrt::guid const& routeId)
    {
        return impl::call_factory<MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([&](IMidiVirtualPatchBayManagerStatics const& f) { return f.GetRoute(routeId); });
    }
    inline auto MidiVirtualPatchBayManager::CreateRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig const& creationConfig)
    {
        return impl::call_factory<MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([&](IMidiVirtualPatchBayManagerStatics const& f) { return f.CreateRoute(creationConfig); });
    }
    inline auto MidiVirtualPatchBayManager::UpdateRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig const& updateConfig)
    {
        return impl::call_factory<MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([&](IMidiVirtualPatchBayManagerStatics const& f) { return f.UpdateRoute(updateConfig); });
    }
    inline auto MidiVirtualPatchBayManager::RemoveRoute(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig const& removalConfig)
    {
        return impl::call_factory<MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([&](IMidiVirtualPatchBayManagerStatics const& f) { return f.RemoveRoute(removalConfig); });
    }
    inline auto MidiVirtualPatchBayManager::GetRouteStatus(winrt::guid const& routeId)
    {
        return impl::call_factory<MidiVirtualPatchBayManager, IMidiVirtualPatchBayManagerStatics>([&](IMidiVirtualPatchBayManagerStatics const& f) { return f.GetRouteStatus(routeId); });
    }
    inline MidiVirtualPatchBayRouteCreationConfig::MidiVirtualPatchBayRouteCreationConfig() :
        MidiVirtualPatchBayRouteCreationConfig(impl::call_factory_cast<MidiVirtualPatchBayRouteCreationConfig(*)(winrt::Windows::Foundation::IActivationFactory const&), MidiVirtualPatchBayRouteCreationConfig>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MidiVirtualPatchBayRouteCreationConfig>(); }))
    {
    }
    inline MidiVirtualPatchBayRouteCreationConfig::MidiVirtualPatchBayRouteCreationConfig(winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition const& definition) :
        MidiVirtualPatchBayRouteCreationConfig(impl::call_factory<MidiVirtualPatchBayRouteCreationConfig, IMidiVirtualPatchBayRouteCreationConfigFactory>([&](IMidiVirtualPatchBayRouteCreationConfigFactory const& f) { return f.CreateInstance(definition); }))
    {
    }
    inline MidiVirtualPatchBayRouteDefinition::MidiVirtualPatchBayRouteDefinition() :
        MidiVirtualPatchBayRouteDefinition(impl::call_factory_cast<MidiVirtualPatchBayRouteDefinition(*)(winrt::Windows::Foundation::IActivationFactory const&), MidiVirtualPatchBayRouteDefinition>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MidiVirtualPatchBayRouteDefinition>(); }))
    {
    }
    inline MidiVirtualPatchBayRouteDefinition::MidiVirtualPatchBayRouteDefinition(param::hstring const& name) :
        MidiVirtualPatchBayRouteDefinition(impl::call_factory<MidiVirtualPatchBayRouteDefinition, IMidiVirtualPatchBayRouteDefinitionFactory>([&](IMidiVirtualPatchBayRouteDefinitionFactory const& f) { return f.CreateInstance(name); }))
    {
    }
    inline MidiVirtualPatchBayRouteDefinition::MidiVirtualPatchBayRouteDefinition(param::hstring const& name, param::hstring const& description) :
        MidiVirtualPatchBayRouteDefinition(impl::call_factory<MidiVirtualPatchBayRouteDefinition, IMidiVirtualPatchBayRouteDefinitionFactory>([&](IMidiVirtualPatchBayRouteDefinitionFactory const& f) { return f.CreateInstance2(name, description); }))
    {
    }
    inline auto MidiVirtualPatchBayRouteDefinition::CreateFromConfigJson(param::hstring const& jsonSection)
    {
        return impl::call_factory<MidiVirtualPatchBayRouteDefinition, IMidiVirtualPatchBayRouteDefinitionStatics>([&](IMidiVirtualPatchBayRouteDefinitionStatics const& f) { return f.CreateFromConfigJson(jsonSection); });
    }
    inline MidiVirtualPatchBayRouteRemovalConfig::MidiVirtualPatchBayRouteRemovalConfig(winrt::guid const& routeId) :
        MidiVirtualPatchBayRouteRemovalConfig(impl::call_factory<MidiVirtualPatchBayRouteRemovalConfig, IMidiVirtualPatchBayRouteRemovalConfigFactory>([&](IMidiVirtualPatchBayRouteRemovalConfigFactory const& f) { return f.CreateInstance(routeId); }))
    {
    }
    inline MidiVirtualPatchBayRouteUpdateConfig::MidiVirtualPatchBayRouteUpdateConfig() :
        MidiVirtualPatchBayRouteUpdateConfig(impl::call_factory_cast<MidiVirtualPatchBayRouteUpdateConfig(*)(winrt::Windows::Foundation::IActivationFactory const&), MidiVirtualPatchBayRouteUpdateConfig>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MidiVirtualPatchBayRouteUpdateConfig>(); }))
    {
    }
    inline MidiVirtualPatchBayRouteUpdateConfig::MidiVirtualPatchBayRouteUpdateConfig(winrt::guid const& routeId) :
        MidiVirtualPatchBayRouteUpdateConfig(impl::call_factory<MidiVirtualPatchBayRouteUpdateConfig, IMidiVirtualPatchBayRouteUpdateConfigFactory>([&](IMidiVirtualPatchBayRouteUpdateConfigFactory const& f) { return f.CreateInstance(routeId); }))
    {
    }
    inline MidiVirtualPatchBaySourceDefinition::MidiVirtualPatchBaySourceDefinition() :
        MidiVirtualPatchBaySourceDefinition(impl::call_factory_cast<MidiVirtualPatchBaySourceDefinition(*)(winrt::Windows::Foundation::IActivationFactory const&), MidiVirtualPatchBaySourceDefinition>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MidiVirtualPatchBaySourceDefinition>(); }))
    {
    }
    inline MidiVirtualPatchBaySourceDefinition::MidiVirtualPatchBaySourceDefinition(winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::MidiServiceConfigEndpointMatchCriteria const& matchCriteria) :
        MidiVirtualPatchBaySourceDefinition(impl::call_factory<MidiVirtualPatchBaySourceDefinition, IMidiVirtualPatchBaySourceDefinitionFactory>([&](IMidiVirtualPatchBaySourceDefinitionFactory const& f) { return f.CreateInstance(matchCriteria); }))
    {
    }
    inline auto MidiVirtualPatchBaySourceDefinition::CreateFromConfigJson(param::hstring const& jsonSection)
    {
        return impl::call_factory<MidiVirtualPatchBaySourceDefinition, IMidiVirtualPatchBaySourceDefinitionStatics>([&](IMidiVirtualPatchBaySourceDefinitionStatics const& f) { return f.CreateFromConfigJson(jsonSection); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinition> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayDestinationDefinitionStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayManagerStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteCreationConfigFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinition> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteDefinitionStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteRemovalConfigFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteStatus> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBayRouteUpdateConfigFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinition> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::IMidiVirtualPatchBaySourceDefinitionStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayDestinationDefinition> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteCreationConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteDefinition> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteRemovalConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteStatus> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBayRouteUpdateConfig> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Microsoft::Windows::Devices::Midi2::VirtualPatchBay::MidiVirtualPatchBaySourceDefinition> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
