// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Microsoft_Windows_Devices_Midi2_Endpoints_BasicLoopback_2_H
#define WINRT_Microsoft_Windows_Devices_Midi2_Endpoints_BasicLoopback_2_H
#include "winrt/impl/Microsoft.Windows.Devices.Midi2.2.h"
#include "winrt/impl/Microsoft.Windows.Devices.Midi2.ServiceConfig.2.h"
#include "winrt/impl/Microsoft.Windows.Devices.Midi2.Endpoints.BasicLoopback.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback
{
    struct MidiBasicLoopbackEndpointCreationResult
    {
        bool Success;
        hstring ErrorInformation;
        winrt::guid AssociationId;
        hstring EndpointDeviceId;
    };
    inline bool operator==(MidiBasicLoopbackEndpointCreationResult const& left, MidiBasicLoopbackEndpointCreationResult const& right) noexcept
    {
        return left.Success == right.Success && left.ErrorInformation == right.ErrorInformation && left.AssociationId == right.AssociationId && left.EndpointDeviceId == right.EndpointDeviceId;
    }
    inline bool operator!=(MidiBasicLoopbackEndpointCreationResult const& left, MidiBasicLoopbackEndpointCreationResult const& right) noexcept
    {
        return !(left == right);
    }
    struct MidiBasicLoopbackEndpointDefinition
    {
        hstring Name;
        hstring UniqueId;
        hstring Description;
        bool IsMuted;
    };
    inline bool operator==(MidiBasicLoopbackEndpointDefinition const& left, MidiBasicLoopbackEndpointDefinition const& right) noexcept
    {
        return left.Name == right.Name && left.UniqueId == right.UniqueId && left.Description == right.Description && left.IsMuted == right.IsMuted;
    }
    inline bool operator!=(MidiBasicLoopbackEndpointDefinition const& left, MidiBasicLoopbackEndpointDefinition const& right) noexcept
    {
        return !(left == right);
    }
    struct WINRT_IMPL_EMPTY_BASES MidiBasicLoopbackEndpointCreationConfig : winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::IMidiBasicLoopbackEndpointCreationConfig,
        impl::require<MidiBasicLoopbackEndpointCreationConfig, winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::IMidiServiceTransportPluginConfig>
    {
        MidiBasicLoopbackEndpointCreationConfig(std::nullptr_t) noexcept {}
        MidiBasicLoopbackEndpointCreationConfig(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::IMidiBasicLoopbackEndpointCreationConfig(ptr, take_ownership_from_abi) {}
        MidiBasicLoopbackEndpointCreationConfig();
        MidiBasicLoopbackEndpointCreationConfig(winrt::guid const& associationId, winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::MidiBasicLoopbackEndpointDefinition const& endpointDefinition);
    };
    struct MidiBasicLoopbackEndpointManager
    {
        MidiBasicLoopbackEndpointManager() = delete;
        [[nodiscard]] static auto IsTransportAvailable();
        [[nodiscard]] static auto TransportId();
        static auto CreateTransientLoopbackEndpoint(winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::MidiBasicLoopbackEndpointCreationConfig const& creationConfig);
        static auto RemoveTransientLoopbackEndpoint(winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::MidiBasicLoopbackEndpointRemovalConfig const& removalConfig);
        static auto GetAssociationId(winrt::Microsoft::Windows::Devices::Midi2::MidiEndpointDeviceInformation const& basicLoopbackEndpoint);
        static auto DoesLoopbackExist(param::hstring const& uniqueIdentifier);
        static auto MuteLoopback(winrt::guid const& associationId);
        static auto UnmuteLoopback(winrt::guid const& associationId);
    };
    struct WINRT_IMPL_EMPTY_BASES MidiBasicLoopbackEndpointRemovalConfig : winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::IMidiBasicLoopbackEndpointRemovalConfig,
        impl::require<MidiBasicLoopbackEndpointRemovalConfig, winrt::Microsoft::Windows::Devices::Midi2::ServiceConfig::IMidiServiceTransportPluginConfig>
    {
        MidiBasicLoopbackEndpointRemovalConfig(std::nullptr_t) noexcept {}
        MidiBasicLoopbackEndpointRemovalConfig(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Windows::Devices::Midi2::Endpoints::BasicLoopback::IMidiBasicLoopbackEndpointRemovalConfig(ptr, take_ownership_from_abi) {}
        explicit MidiBasicLoopbackEndpointRemovalConfig(winrt::guid const& associationId);
    };
}
#endif
